---
sudo: required
language: objective-c
osx_image: xcode11

before_install:
  - cd Dependencies
  - git clone https://github.com/GPGTools/Libmacgpg.git
  - cd ..


install:
  - brew install gnupg

script:
  - make
  
